### ISSUE TITLE
Integration of angular grid

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#23]
The idea is to use [AngularJS grid](http://ui-grid.info/) to display tables.
The integration should work with the Javascript API client.

**Comment by tazo90** [comment]
[Branch](https://github.com/tazo90/lux/tree/issue23)

**Comment by lsbardel** [comment]
From python side we need an html component which trigger the AngularJS directive. The compoent shoudl create an html entry of the form
```html
<div ng-controller="RestGrid">
    <div ui-grid="gridxyz" class="grid"></div>
    <script>
        if (!this.luxgrids) this.luxgrids = {};
        this.luxgrids.gridxyz = {...};
    </script>
</div>
```

**Comment by tazo90** [comment]
@lsbardel basic integration is done.

**Comment by tazo90** [comment]
@lsbardel Added `select` for boolean fields and external sorting (currently one column at the same time).

1. Could I send the same key (sortby) with different values using `$api.get`? 
I would need something like this `sortby=<key>:desc&sortby=<key>:asc` to pass in params.


Currently is supported only one column sorting at the same time, because get method of the api accept object only, so we can't pass something like this:

`api.get({}, {sortby: 'username', sortby: 'email'}).success(function(resp) {
    scope.gridOptions.data = resp.result;
});`

Adding support for multiple column sorting is fairly easy from the grid side.

Remains to be done:
- filtering support for the API.
- extend `$api.get` to support params (keys) with the same value, it solves issue for sorting multiple column.

**Comment by lsbardel** [comment]
This works well, I'll create separate issue for new features
